package admin

import (
	"crypto/rand"
	"database/sql"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"net/url"
	"strings"
	"sync"
	"time"

	"controller/state"

	"golang.org/x/oauth2"
	"golang.org/x/oauth2/google"
)

// oauthStateEntry holds a CSRF state value with its expiry.
type oauthStateEntry struct {
	value     string
	expiresAt time.Time
}

var (
	oauthStateMu    sync.Mutex
	oauthStateStore = map[string]oauthStateEntry{}
)

func randomHex(n int) (string, error) {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return hex.EncodeToString(b), nil
}

func storeOAuthState(state string) {
	oauthStateMu.Lock()
	defer oauthStateMu.Unlock()
	oauthStateStore[state] = oauthStateEntry{value: state, expiresAt: time.Now().Add(10 * time.Minute)}
	// Prune expired states
	for k, v := range oauthStateStore {
		if time.Now().After(v.expiresAt) {
			delete(oauthStateStore, k)
		}
	}
}

func consumeOAuthState(state string) bool {
	oauthStateMu.Lock()
	defer oauthStateMu.Unlock()
	entry, ok := oauthStateStore[state]
	if !ok || time.Now().After(entry.expiresAt) {
		return false
	}
	delete(oauthStateStore, state)
	return true
}

// handleOAuthLogin redirects the user to Google's consent screen.
func (s *Server) handleOAuthLogin(w http.ResponseWriter, r *http.Request) {
	if s.OAuthConfig == nil {
		http.Error(w, "OAuth not configured", http.StatusServiceUnavailable)
		return
	}
	csrfState, err := randomHex(16)
	if err != nil {
		http.Error(w, "internal error", http.StatusInternalServerError)
		return
	}
	storeOAuthState(csrfState)
	authURL := s.OAuthConfig.AuthCodeURL(csrfState, oauth2.AccessTypeOnline)
	http.Redirect(w, r, authURL, http.StatusFound)
}

// handleOAuthCallback handles the redirect from Google after user consent.
func (s *Server) handleOAuthCallback(w http.ResponseWriter, r *http.Request) {
	if s.OAuthConfig == nil {
		http.Error(w, "OAuth not configured", http.StatusServiceUnavailable)
		return
	}
	stateParam := r.URL.Query().Get("state")
	code := r.URL.Query().Get("code")

	// Detect invite flow: state is "invite:<token>"
	isInvite := strings.HasPrefix(stateParam, "invite:")
	var inviteToken string
	csrfState := stateParam
	if isInvite {
		inviteToken = strings.TrimPrefix(stateParam, "invite:")
		// The CSRF state for invite flows is the invite token itself (already random).
		// Re-use it as the state key so we can verify it was generated by us.
		if !consumeOAuthState(stateParam) {
			http.Error(w, "invalid or expired state", http.StatusBadRequest)
			return
		}
	} else {
		if !consumeOAuthState(csrfState) {
			http.Error(w, "invalid or expired state", http.StatusBadRequest)
			return
		}
	}

	token, err := s.OAuthConfig.Exchange(r.Context(), code)
	if err != nil {
		http.Error(w, "token exchange failed", http.StatusBadRequest)
		return
	}

	// Fetch the user's email from Google's userinfo endpoint.
	client := s.OAuthConfig.Client(r.Context(), token)
	resp, err := client.Get("https://www.googleapis.com/oauth2/v3/userinfo")
	if err != nil {
		http.Error(w, "failed to get user info", http.StatusInternalServerError)
		return
	}
	defer resp.Body.Close()

	var info struct {
		Email string `json:"email"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&info); err != nil || info.Email == "" {
		http.Error(w, "failed to parse user info", http.StatusInternalServerError)
		return
	}
	email := strings.ToLower(info.Email)

	db := s.db()

	if isInvite {
		if db == nil {
			http.Error(w, "database not available", http.StatusInternalServerError)
			return
		}
		var invitedEmail string
		var expiresAt int64
		var used int
		err := db.QueryRow(
			state.Rebind(`SELECT email, expires_at, used FROM invite_tokens WHERE token = ?`), inviteToken,
		).Scan(&invitedEmail, &expiresAt, &used)
		if err == sql.ErrNoRows {
			http.Error(w, "invite token not found", http.StatusBadRequest)
			return
		}
		if err != nil {
			http.Error(w, "database error", http.StatusInternalServerError)
			return
		}
		if used != 0 {
			http.Error(w, "invite token already used", http.StatusBadRequest)
			return
		}
		if time.Now().Unix() > expiresAt {
			http.Error(w, "invite token expired", http.StatusBadRequest)
			return
		}
		if strings.ToLower(invitedEmail) != email {
			http.Error(w, "Google account does not match the invited email", http.StatusForbidden)
			return
		}

		// Create the user record.
		if s.Users != nil {
			user := state.User{
				Name:      email,
				Email:     email,
				Status:    "Active",
				Role:      "Member",
				CreatedAt: time.Now().UTC(),
				UpdatedAt: time.Now().UTC(),
			}
			if createErr := s.Users.CreateUser(&user); createErr != nil {
				log.Printf("invite: failed to create user %s: %v", email, createErr)
			}
		}

		// Mark invite token as used.
		_, _ = db.Exec(state.Rebind(`UPDATE invite_tokens SET used = 1 WHERE token = ?`), inviteToken)
		s.writeAdminAudit(db, email, "invite_redeemed", email, "ok")
	} else {
		// Regular login: verify email is in the allowed list.
		if len(s.AdminLoginEmails) > 0 {
			if _, ok := s.AdminLoginEmails[email]; !ok {
				http.Error(w, "email not authorised", http.StatusForbidden)
				return
			}
		}
		if db != nil {
			s.writeAdminAudit(db, email, "admin_login", email, "ok")
		}
	}

	jwtToken, err := s.signSessionJWT(email)
	if err != nil {
		http.Error(w, "failed to create session", http.StatusInternalServerError)
		return
	}
	s.setSessionCookie(w, jwtToken)

	dashboardURL := s.DashboardURL
	if dashboardURL == "" {
		dashboardURL = "http://localhost:5173"
	}
	redirect := fmt.Sprintf("%s?token=%s", dashboardURL, url.QueryEscape(jwtToken))
	http.Redirect(w, r, redirect, http.StatusFound)
}

// handleOAuthLogout clears the session cookie.
func (s *Server) handleOAuthLogout(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	email := ""
	if len(s.JWTSecret) > 0 {
		email, _ = s.sessionFromRequest(r)
	}
	s.clearSessionCookie(w)
	if db := s.db(); db != nil && email != "" {
		s.writeAdminAudit(db, email, "admin_logout", email, "ok")
	}
	writeJSON(w, http.StatusOK, map[string]string{"status": "logged out"})
}

// handleInviteAccept validates an invite token and starts the OAuth flow.
// GET /invite?token=<token>
func (s *Server) handleInviteAccept(w http.ResponseWriter, r *http.Request) {
	if s.OAuthConfig == nil {
		http.Error(w, "OAuth not configured", http.StatusServiceUnavailable)
		return
	}
	token := r.URL.Query().Get("token")
	if token == "" {
		http.Error(w, "missing token", http.StatusBadRequest)
		return
	}
	db := s.db()
	if db == nil {
		http.Error(w, "database not available", http.StatusInternalServerError)
		return
	}
	var expiresAt int64
	var used int
	err := db.QueryRow(state.Rebind(`SELECT expires_at, used FROM invite_tokens WHERE token = ?`), token).
		Scan(&expiresAt, &used)
	if err == sql.ErrNoRows {
		http.Error(w, "invite token not found", http.StatusNotFound)
		return
	}
	if err != nil {
		http.Error(w, "database error", http.StatusInternalServerError)
		return
	}
	if used != 0 {
		http.Error(w, "invite token already used", http.StatusGone)
		return
	}
	if time.Now().Unix() > expiresAt {
		http.Error(w, "invite token expired", http.StatusGone)
		return
	}

	// Embed the invite token in the OAuth state so it survives the redirect round-trip.
	oauthState := "invite:" + token
	storeOAuthState(oauthState)
	authURL := s.OAuthConfig.AuthCodeURL(oauthState, oauth2.AccessTypeOnline)
	http.Redirect(w, r, authURL, http.StatusFound)
}

// handleInviteUser sends an invite email.
// POST /api/admin/users/invite
func (s *Server) handleInviteUser(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	var req struct {
		Email string `json:"email"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil || req.Email == "" {
		http.Error(w, "email is required", http.StatusBadRequest)
		return
	}
	email := strings.ToLower(strings.TrimSpace(req.Email))

	db := s.db()
	if db == nil {
		http.Error(w, "database not available", http.StatusInternalServerError)
		return
	}

	inviteToken, err := randomHex(24)
	if err != nil {
		http.Error(w, "internal error", http.StatusInternalServerError)
		return
	}
	expiresAt := time.Now().Add(48 * time.Hour).Unix()
	_, err = db.Exec(
		state.Rebind(`INSERT INTO invite_tokens (token, email, expires_at, used) VALUES (?, ?, ?, 0)`),
		inviteToken, email, expiresAt,
	)
	if err != nil {
		http.Error(w, fmt.Sprintf("failed to create invite token: %v", err), http.StatusInternalServerError)
		return
	}

	inviteBaseURL := s.InviteBaseURL
	if inviteBaseURL == "" {
		inviteBaseURL = "http://localhost:8081"
	}
	inviteURL := fmt.Sprintf("%s/invite?token=%s", inviteBaseURL, inviteToken)

	if s.Mailer != nil {
		if mailErr := s.Mailer.SendInvite(email, inviteURL); mailErr != nil {
			log.Printf("invite: failed to send email to %s: %v", email, mailErr)
			http.Error(w, "failed to send invite email", http.StatusInternalServerError)
			return
		}
	} else {
		log.Printf("invite: SMTP not configured; invite URL for %s: %s", email, inviteURL)
	}

	actor := sessionEmailFromContext(r.Context())
	if actor == "" {
		actor = "admin"
	}
	s.writeAdminAudit(db, actor, "invite_sent", email, "ok")

	writeJSON(w, http.StatusOK, map[string]interface{}{
		"status":     "invited",
		"email":      email,
		"invite_url": inviteURL,
	})
}

// handleAdminAuditLogs returns paginated admin audit log entries.
// GET /api/admin/audit-logs?limit=50&offset=0
func (s *Server) handleAdminAuditLogs(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	db := s.db()
	if db == nil {
		writeJSON(w, http.StatusOK, []interface{}{})
		return
	}

	limit := 50
	offset := 0
	if v := r.URL.Query().Get("limit"); v != "" {
		fmt.Sscanf(v, "%d", &limit)
	}
	if v := r.URL.Query().Get("offset"); v != "" {
		fmt.Sscanf(v, "%d", &offset)
	}
	if limit > 500 {
		limit = 500
	}

	rows, err := db.Query(
		state.Rebind(`SELECT id, timestamp, actor, action, target, result FROM admin_audit_logs ORDER BY id DESC LIMIT ? OFFSET ?`),
		limit, offset,
	)
	if err != nil {
		http.Error(w, "failed to query audit logs", http.StatusInternalServerError)
		return
	}
	defer rows.Close()

	type entry struct {
		ID        int64  `json:"id"`
		Timestamp int64  `json:"timestamp"`
		Actor     string `json:"actor"`
		Action    string `json:"action"`
		Target    string `json:"target"`
		Result    string `json:"result"`
	}
	out := []entry{}
	for rows.Next() {
		var e entry
		if err := rows.Scan(&e.ID, &e.Timestamp, &e.Actor, &e.Action, &e.Target, &e.Result); err != nil {
			http.Error(w, "scan error", http.StatusInternalServerError)
			return
		}
		out = append(out, e)
	}
	writeJSON(w, http.StatusOK, out)
}

// writeAdminAudit inserts a row into admin_audit_logs.
func (s *Server) writeAdminAudit(db *sql.DB, actor, action, target, result string) {
	_, err := db.Exec(
		state.Rebind(`INSERT INTO admin_audit_logs (timestamp, actor, action, target, result) VALUES (?, ?, ?, ?, ?)`),
		time.Now().Unix(), actor, action, target, result,
	)
	if err != nil {
		log.Printf("audit: failed to write admin audit log: %v", err)
	}
}

// BuildOAuthConfig returns a configured *oauth2.Config if clientID is set, otherwise nil.
func BuildOAuthConfig(clientID, clientSecret, redirectURL string) *oauth2.Config {
	if clientID == "" {
		return nil
	}
	return &oauth2.Config{
		ClientID:     clientID,
		ClientSecret: clientSecret,
		RedirectURL:  redirectURL,
		Scopes:       []string{"https://www.googleapis.com/auth/userinfo.email"},
		Endpoint:     google.Endpoint,
	}
}
